apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"hello-world:hello-world"},"fieldPath":"spec.template.spec.containers[?(@.name==\"hello-world\")].image"}]'
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: "2024-04-29T14:14:49Z"
  generation: 2
  labels:
    app: hello-world
    app.kubernetes.io/component: hello-world
    app.kubernetes.io/instance: hello-world
  name: hello-world
  namespace: hello-world
  resourceVersion: "4634663"
  uid: aa926665-67c0-4815-a63b-631832c8164a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: hello-world
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deployment: hello-world
    spec:
      containers:
      - image: quay-server.apps.shanearotest.eastus.aroapp.io/python-app/testapp@sha256:9aa61fc42f41be08c8c0ccf1db6642a135d16b60dc66d00c53863df5494dfc88
        imagePullPolicy: IfNotPresent
        name: hello-world
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-04-29T14:14:52Z"
    lastUpdateTime: "2024-04-29T14:14:52Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-04-29T14:14:50Z"
    lastUpdateTime: "2024-04-29T14:14:52Z"
    message: ReplicaSet "hello-world-86b899d569" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
