apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: 'gitops-demo:apps/Deployment:hello-world/hello-world'
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: "2024-04-29T14:14:49Z"
  labels:
    app: hello-world
    app.kubernetes.io/component: hello-world
    app.kubernetes.io/instance: hello-world
  name: hello-world
  namespace: hello-world
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: hello-world
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deployment: hello-world
    spec:
      containers:
      - image: quay-server.apps.shanearotest.eastus.aroapp.io/python-app/testapp@sha256:9aa61fc42f41be08c8c0ccf1db6642a135d16b60dc66d00c53863df5494dfc88
        imagePullPolicy: IfNotPresent
        name: hello-world
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
