apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: "2024-04-29T14:14:50Z"
  labels:
    app: hello-world
    app.kubernetes.io/component: hello-world
    app.kubernetes.io/instance: hello-world
  name: hello-world
  namespace: hello-world
  resourceVersion: "4634586"
  uid: f0a6f9f4-99bf-4d75-ad2d-f0d5e8c7d8bc
spec:
  clusterIP: 172.30.159.80
  clusterIPs:
  - 172.30.159.80
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 5000-tcp
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    deployment: hello-world
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
